version: "3.9"

services:
  php:
    build: .
    image: php:8.4-apache
    container_name: php_app
    ports:
      - "8080:80"
    volumes:
      - ..:/var/www
    working_dir: /var/www/public_html
    restart: "no"